/*
-- Query: SELECT * FROM skyrate.country
-- Date: 2018-05-29 10:30
*/
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (1,'AF','Afghanistan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (2,'AX','Åland Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (3,'AL','Albania');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (4,'DZ','Algeria');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (5,'AS','American Samoa');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (6,'AD','AndorrA');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (7,'AO','Angola');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (8,'AI','Anguilla');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (9,'AQ','Antarctica');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (10,'AG','Antigua and Barbuda');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (11,'AR','Argentina');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (12,'AM','Armenia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (13,'AW','Aruba');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (14,'AU','Australia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (15,'AT','Austria');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (16,'AZ','Azerbaijan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (17,'BS','Bahamas');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (18,'BH','Bahrain');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (19,'BD','Bangladesh');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (20,'BB','Barbados');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (21,'BY','Belarus');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (22,'BE','Belgium');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (23,'BZ','Belize');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (24,'BJ','Benin');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (25,'BM','Bermuda');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (26,'BT','Bhutan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (27,'BO','Bolivia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (28,'BA','Bosnia and Herzegovina');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (29,'BW','Botswana');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (30,'BV','Bouvet Island');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (31,'BR','Brazil');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (32,'IO','British Indian Ocean Territory');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (33,'BN','Brunei Darussalam');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (34,'BG','Bulgaria');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (35,'BF','Burkina Faso');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (36,'BI','Burundi');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (37,'KH','Cambodia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (38,'CM','Cameroon');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (39,'CA','Canada');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (40,'CV','Cape Verde');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (41,'KY','Cayman Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (42,'CF','Central African Republic');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (43,'TD','Chad');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (44,'CL','Chile');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (45,'CN','China');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (46,'CX','Christmas Island');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (47,'CC','Cocos (Keeling) Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (48,'CO','Colombia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (49,'KM','Comoros');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (50,'CG','Congo');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (51,'CD','Congo, The Democratic Republic of the');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (52,'CK','Cook Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (53,'CR','Costa Rica');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (54,'CI','Cote D\'Ivoire');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (55,'HR','Croatia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (56,'CU','Cuba');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (57,'CY','Cyprus');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (58,'CZ','Czech Republic');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (59,'DK','Denmark');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (60,'DJ','Djibouti');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (61,'DM','Dominica');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (62,'DO','Dominican Republic');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (63,'EC','Ecuador');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (64,'EG','Egypt');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (65,'SV','El Salvador');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (66,'GQ','Equatorial Guinea');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (67,'ER','Eritrea');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (68,'EE','Estonia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (69,'ET','Ethiopia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (70,'FK','Falkland Islands (Malvinas)');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (71,'FO','Faroe Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (72,'FJ','Fiji');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (73,'FI','Finland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (74,'FR','France');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (75,'GF','French Guiana');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (76,'PF','French Polynesia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (77,'TF','French Southern Territories');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (78,'GA','Gabon');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (79,'GM','Gambia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (80,'GE','Georgia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (81,'DE','Germany');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (82,'GH','Ghana');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (83,'GI','Gibraltar');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (84,'GR','Greece');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (85,'GL','Greenland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (86,'GD','Grenada');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (87,'GP','Guadeloupe');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (88,'GU','Guam');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (89,'GT','Guatemala');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (90,'GG','Guernsey');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (91,'GN','Guinea');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (92,'GW','Guinea-Bissau');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (93,'GY','Guyana');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (94,'HT','Haiti');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (95,'HM','Heard Island and Mcdonald Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (96,'VA','Holy See (Vatican City State)');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (97,'HN','Honduras');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (98,'HK','Hong Kong');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (99,'HU','Hungary');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (100,'IS','Iceland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (101,'IN','India');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (102,'ID','Indonesia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (103,'IR','Iran, Islamic Republic Of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (104,'IQ','Iraq');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (105,'IE','Ireland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (106,'IM','Isle of Man');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (107,'IL','Israel');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (108,'IT','Italy');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (109,'JM','Jamaica');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (110,'JP','Japan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (111,'JE','Jersey');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (112,'JO','Jordan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (113,'KZ','Kazakhstan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (114,'KE','Kenya');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (115,'KI','Kiribati');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (116,'KP','Korea, Democratic People\'S Republic of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (117,'KR','Korea, Republic of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (118,'KW','Kuwait');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (119,'KG','Kyrgyzstan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (120,'LA','Lao People\'S Democratic Republic');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (121,'LV','Latvia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (122,'LB','Lebanon');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (123,'LS','Lesotho');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (124,'LR','Liberia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (125,'LY','Libyan Arab Jamahiriya');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (126,'LI','Liechtenstein');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (127,'LT','Lithuania');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (128,'LU','Luxembourg');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (129,'MO','Macao');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (130,'MK','Macedonia, The Former Yugoslav Republic of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (131,'MG','Madagascar');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (132,'MW','Malawi');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (133,'MY','Malaysia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (134,'MV','Maldives');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (135,'ML','Mali');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (136,'MT','Malta');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (137,'MH','Marshall Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (138,'MQ','Martinique');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (139,'MR','Mauritania');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (140,'MU','Mauritius');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (141,'YT','Mayotte');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (142,'MX','Mexico');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (143,'FM','Micronesia, Federated States of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (144,'MD','Moldova, Republic of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (145,'MC','Monaco');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (146,'MN','Mongolia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (147,'MS','Montserrat');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (148,'MA','Morocco');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (149,'MZ','Mozambique');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (150,'MM','Myanmar');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (151,'NA','Namibia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (152,'NR','Nauru');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (153,'NP','Nepal');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (154,'NL','Netherlands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (155,'AN','Netherlands Antilles');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (156,'NC','New Caledonia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (157,'NZ','New Zealand');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (158,'NI','Nicaragua');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (159,'NE','Niger');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (160,'NG','Nigeria');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (161,'NU','Niue');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (162,'NF','Norfolk Island');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (163,'MP','Northern Mariana Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (164,'NO','Norway');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (165,'OM','Oman');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (166,'PK','Pakistan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (167,'PW','Palau');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (168,'PS','Palestinian Territory, Occupied');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (169,'PA','Panama');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (170,'PG','Papua New Guinea');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (171,'PY','Paraguay');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (172,'PE','Peru');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (173,'PH','Philippines');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (174,'PN','Pitcairn');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (175,'PL','Poland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (176,'PT','Portugal');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (177,'PR','Puerto Rico');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (178,'QA','Qatar');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (179,'RE','Reunion');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (180,'RO','Romania');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (181,'RU','Russian Federation');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (182,'RW','RWANDA');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (183,'SH','Saint Helena');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (184,'KN','Saint Kitts and Nevis');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (185,'LC','Saint Lucia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (186,'PM','Saint Pierre and Miquelon');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (187,'VC','Saint Vincent and the Grenadines');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (188,'WS','Samoa');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (189,'SM','San Marino');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (190,'ST','Sao Tome and Principe');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (191,'SA','Saudi Arabia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (192,'SN','Senegal');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (193,'CS','Serbia and Montenegro');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (194,'SC','Seychelles');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (195,'SL','Sierra Leone');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (196,'SG','Singapore');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (197,'SK','Slovakia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (198,'SI','Slovenia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (199,'SB','Solomon Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (200,'SO','Somalia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (201,'ZA','South Africa');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (202,'GS','South Georgia and the South Sandwich Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (203,'ES','Spain');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (204,'LK','Sri Lanka');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (205,'SD','Sudan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (206,'SR','Suriname');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (207,'SJ','Svalbard and Jan Mayen');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (208,'SZ','Swaziland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (209,'SE','Sweden');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (210,'CH','Switzerland');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (211,'SY','Syrian Arab Republic');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (212,'TW','Taiwan, Province of China');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (213,'TJ','Tajikistan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (214,'TZ','Tanzania, United Republic of');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (215,'TH','Thailand');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (216,'TL','Timor-Leste');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (217,'TG','Togo');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (218,'TK','Tokelau');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (219,'TO','Tonga');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (220,'TT','Trinidad and Tobago');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (221,'TN','Tunisia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (222,'TR','Turkey');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (223,'TM','Turkmenistan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (224,'TC','Turks and Caicos Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (225,'TV','Tuvalu');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (226,'UG','Uganda');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (227,'UA','Ukraine');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (228,'AE','United Arab Emirates');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (229,'GB','United Kingdom');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (230,'US','United States');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (231,'UM','United States Minor Outlying Islands');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (232,'UY','Uruguay');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (233,'UZ','Uzbekistan');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (234,'VU','Vanuatu');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (235,'VE','Venezuela');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (236,'VN','Viet Nam');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (237,'VG','Virgin Islands, British');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (238,'VI','Virgin Islands, U.S.');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (239,'WF','Wallis and Futuna');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (240,'EH','Western Sahara');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (241,'YE','Yemen');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (242,'ZM','Zambia');
INSERT INTO `country` (`ID`,`CODE`,`NAME`) VALUES (243,'ZW','Zimbabwe');
